name: Update YouTube Playlist

on:
  schedule:
    - cron: '0 0 * * *' # Τρέχει κάθε μέρα τα μεσάνυχτα
  workflow_dispatch: # Επιτρέπει χειροκίνητη εκτέλεση

# Δίνουμε δικαιώματα εγγραφής στο script
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Generate M3U Playlist
      run: |
        # Καθαρισμός/Δημιουργία αρχείου
        echo "#EXTM3U" > playlist.m3u
        
        # --- ΛΙΣΤΑ 1: VILLAGE CINEMAS ---
        PLAYLIST_ID_1="PL2rB3_wxnzkSPdWlqnGO3FGmg8HObgy20"
        yt-dlp --flat-playlist --print "%(title)s,%(id)s" "https://www.youtube.com/playlist?list=$PLAYLIST_ID_1" | while IFS=, read -r title id; do
            echo "#EXTINF:-1 group-title=\"Village Cinemas Trailers\" tvg-logo=\"https://raw.githubusercontent.com/manolischania/manalab-iptv/refs/heads/main/logo/village.png\",$title" >> playlist.m3u
            echo "plugin://plugin.video.youtube/play/?video_id=$id" >> playlist.m3u
        done

        # --- ΛΙΣΤΑ 2: ODEON ---
        PLAYLIST_ID_2="PL4Y7FFH8ohQqwRz472oHk7soTuIBGGUm0"
        yt-dlp --flat-playlist --print "%(title)s,%(id)s" "https://www.youtube.com/playlist?list=$PLAYLIST_ID_2" | while IFS=, read -r title id; do
            echo "#EXTINF:-1 group-title=\"Odeon Cinema Trailers\" tvg-logo=\"https://raw.githubusercontent.com/manolischania/manalab-iptv/refs/heads/main/logo/odeon.png\",$title" >> playlist.m3u
            echo "plugin://plugin.video.youtube/play/?video_id=$id" >> playlist.m3u
        done
        
        # --- ΛΙΣΤΑ 3: FEELGOOD ---
        PLAYLIST_ID_3="PLEq9lv6PlXlLMyI1cxwkza0r8kcSxVxz_"
        yt-dlp --flat-playlist --print "%(title)s,%(id)s" "https://www.youtube.com/playlist?list=$PLAYLIST_ID_3" | while IFS=, read -r title id; do
            echo "#EXTINF:-1 group-title=\"Feelgood Ent. Trailers\" tvg-logo=\"https://raw.githubusercontent.com/manolischania/manalab-iptv/refs/heads/main/logo/feelgood.png\",$title" >> playlist.m3u
            echo "plugin://plugin.video.youtube/play/?video_id=$id" >> playlist.m3u
        done

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add playlist.m3u
        # Ελέγχει αν υπάρχουν αλλαγές πριν κάνει commit για να μην βγάλει error
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update playlist"
          git push
        fi
